/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 4.9 */
/* Sun Jan 29 15:33:05 2017 */

/* parameterized module instance */
mult __ (.DataA( ), .DataB( ), .Result( ));
