/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 5.7 */
/* Thu Jan 05 20:20:56 2017 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ));
