/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 1.6 */
/* C:\lscc\diamond\3.8_x64\ispfpga\bin\nt64\scuba.exe -w -n sincos -lang verilog -synth synplify -bus_exp 7 -bb -arch xo3c00f -type cosine -addr_width 10 -width 16 -input_reg -mode 4 -area -pipeline 1  */
/* Mon Jan 02 18:22:07 2017 */


`timescale 1 ns / 1 ps
module sincos (Clock, ClkEn, Reset, Theta, Sine)/* synthesis NGD_DRC_MASK=1 */;
    input wire Clock;
    input wire ClkEn;
    input wire Reset;
    input wire [9:0] Theta;
    output wire [15:0] Sine;

    wire func_or_inet_1;
    wire func_or_inet;
    wire lx_ne0;
    wire lx_ne0_inv;
    wire mx_ctrl_r_inv;
    wire rom_addr0_r_n_8;
    wire rom_addr0_r;
    wire rom_addr0_r_n_9;
    wire rom_addr0_r_1;
    wire rom_addr0_r_n_10;
    wire rom_addr0_r_2;
    wire rom_addr0_r_n_11;
    wire rom_addr0_r_3;
    wire rom_addr0_r_n_12;
    wire rom_addr0_r_4;
    wire rom_addr0_r_n_13;
    wire rom_addr0_r_5;
    wire rom_addr0_r_n_14;
    wire rom_addr0_r_6;
    wire rom_addr0_r_n_15;
    wire mx_ctrl_r;
    wire rom_addr0_r_7;
    wire mx_ctrl_r_1;
    wire rom_dout;
    wire rom_dout_1;
    wire rom_dout_2;
    wire rom_dout_3;
    wire rom_dout_4;
    wire rom_dout_5;
    wire rom_dout_6;
    wire rom_dout_7;
    wire rom_dout_8;
    wire rom_dout_9;
    wire rom_dout_10;
    wire rom_dout_11;
    wire rom_dout_12;
    wire rom_dout_13;
    wire rom_dout_14;
    wire sinromoutsel;
    wire rom_dout_15;
    wire out_sel_i;
    wire rom_dout_16;
    wire rom_dout_17;
    wire rom_dout_18;
    wire rom_dout_19;
    wire rom_dout_20;
    wire rom_dout_21;
    wire rom_dout_22;
    wire rom_dout_23;
    wire rom_dout_24;
    wire rom_dout_25;
    wire rom_dout_26;
    wire rom_dout_27;
    wire rom_dout_28;
    wire rom_dout_29;
    wire rom_dout_30;
    wire out_sel;
    wire rom_dout_31;
    wire rom_addr0_r_n;
    wire rom_addr0_r_inv;
    wire rom_addr0_r_n_1;
    wire rom_addr0_r_n_2;
    wire co0;
    wire rom_addr0_r_1_inv;
    wire rom_addr0_r_2_inv;
    wire rom_addr0_r_n_3;
    wire rom_addr0_r_n_4;
    wire co1;
    wire rom_addr0_r_3_inv;
    wire rom_addr0_r_4_inv;
    wire rom_addr0_r_n_5;
    wire rom_addr0_r_n_6;
    wire co2;
    wire rom_addr0_r_5_inv;
    wire rom_addr0_r_6_inv;
    wire rom_addr0_r_n_7;
    wire co3;
    wire rom_addr0_r_7_inv;
    wire rom_dout_n;
    wire scuba_vhi;
    wire rom_dout_inv;
    wire rom_dout_n_1;
    wire rom_dout_n_2;
    wire co0_1;
    wire rom_dout_1_inv;
    wire rom_dout_2_inv;
    wire rom_dout_n_3;
    wire rom_dout_n_4;
    wire co1_1;
    wire rom_dout_3_inv;
    wire rom_dout_4_inv;
    wire rom_dout_n_5;
    wire rom_dout_n_6;
    wire co2_1;
    wire rom_dout_5_inv;
    wire rom_dout_6_inv;
    wire rom_dout_n_7;
    wire rom_dout_n_8;
    wire co3_1;
    wire rom_dout_7_inv;
    wire rom_dout_8_inv;
    wire rom_dout_n_9;
    wire rom_dout_n_10;
    wire co4;
    wire rom_dout_9_inv;
    wire rom_dout_10_inv;
    wire rom_dout_n_11;
    wire rom_dout_n_12;
    wire co5;
    wire rom_dout_11_inv;
    wire rom_dout_12_inv;
    wire rom_dout_n_13;
    wire rom_dout_n_14;
    wire co6;
    wire rom_dout_13_inv;
    wire rom_dout_14_inv;
    wire rom_dout_n_15;
    wire co7;
    wire rom_dout_15_inv;
    wire scuba_vlo;

    INV INV_25 (.A(rom_addr0_r_7), .Z(rom_addr0_r_7_inv));

    INV INV_24 (.A(rom_addr0_r_6), .Z(rom_addr0_r_6_inv));

    INV INV_23 (.A(rom_addr0_r_5), .Z(rom_addr0_r_5_inv));

    INV INV_22 (.A(rom_addr0_r_4), .Z(rom_addr0_r_4_inv));

    INV INV_21 (.A(rom_addr0_r_3), .Z(rom_addr0_r_3_inv));

    INV INV_20 (.A(rom_addr0_r_2), .Z(rom_addr0_r_2_inv));

    INV INV_19 (.A(rom_addr0_r_1), .Z(rom_addr0_r_1_inv));

    INV INV_18 (.A(rom_addr0_r), .Z(rom_addr0_r_inv));

    INV INV_17 (.A(rom_dout_15), .Z(rom_dout_15_inv));

    INV INV_16 (.A(rom_dout_14), .Z(rom_dout_14_inv));

    INV INV_15 (.A(rom_dout_13), .Z(rom_dout_13_inv));

    INV INV_14 (.A(rom_dout_12), .Z(rom_dout_12_inv));

    INV INV_13 (.A(rom_dout_11), .Z(rom_dout_11_inv));

    INV INV_12 (.A(rom_dout_10), .Z(rom_dout_10_inv));

    INV INV_11 (.A(rom_dout_9), .Z(rom_dout_9_inv));

    INV INV_10 (.A(rom_dout_8), .Z(rom_dout_8_inv));

    INV INV_9 (.A(rom_dout_7), .Z(rom_dout_7_inv));

    INV INV_8 (.A(rom_dout_6), .Z(rom_dout_6_inv));

    INV INV_7 (.A(rom_dout_5), .Z(rom_dout_5_inv));

    INV INV_6 (.A(rom_dout_4), .Z(rom_dout_4_inv));

    INV INV_5 (.A(rom_dout_3), .Z(rom_dout_3_inv));

    INV INV_4 (.A(rom_dout_2), .Z(rom_dout_2_inv));

    INV INV_3 (.A(rom_dout_1), .Z(rom_dout_1_inv));

    INV INV_2 (.A(rom_dout), .Z(rom_dout_inv));

    defparam LUT4_2.initval =  16'hfffe ;
    ROM16X1A LUT4_2 (.AD3(rom_addr0_r_n_8), .AD2(rom_addr0_r_n_9), .AD1(rom_addr0_r_n_10), 
        .AD0(rom_addr0_r_n_11), .DO0(func_or_inet));

    defparam LUT4_1.initval =  16'hfffe ;
    ROM16X1A LUT4_1 (.AD3(rom_addr0_r_n_12), .AD2(rom_addr0_r_n_13), .AD1(rom_addr0_r_n_14), 
        .AD0(rom_addr0_r_n_15), .DO0(func_or_inet_1));

    defparam LUT4_0.initval =  16'hfffe ;
    ROM16X1A LUT4_0 (.AD3(func_or_inet), .AD2(func_or_inet_1), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(lx_ne0));

    INV INV_1 (.A(lx_ne0), .Z(lx_ne0_inv));

    INV INV_0 (.A(mx_ctrl_r), .Z(mx_ctrl_r_inv));

    AND2 AND2_t0 (.A(mx_ctrl_r_inv), .B(lx_ne0_inv), .Z(out_sel_i));

    defparam triglut_1_0_0_0.INIT_DATA = "STATIC" ;
    defparam triglut_1_0_0_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam triglut_1_0_0_0.INITVAL_1F = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_1E = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_1D = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_1C = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_1B = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_1A = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_19 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_18 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_17 = "0x00000002010020200403006030080400A0500A0600C0700E0701008012090120A0140A0160B0180C" ;
    defparam triglut_1_0_0_0.INITVAL_16 = "0x0180D01A0E01C0E01E0F01E1002011022110241202413026140281402A1502A1602C1702E1703018" ;
    defparam triglut_1_0_0_0.INITVAL_15 = "0x03019032190341A0361B0361C0381C03A1D03A1E03C1E03E1F03E200402004221042220442204623" ;
    defparam triglut_1_0_0_0.INITVAL_14 = "0x046240482404A2504A2604C2604E2704E270502805029052290542A0542A0562B0562C0582C0582D" ;
    defparam triglut_1_0_0_0.INITVAL_13 = "0x05A2D05C2E05C2E05E2F05E2F0603006030062310623106432064320663306633068340683406835" ;
    defparam triglut_1_0_0_0.INITVAL_12 = "0x06A3506A3606C3606C3606E3706E3706E3807038070380703907239072390743A0743A0743A0743B" ;
    defparam triglut_1_0_0_0.INITVAL_11 = "0x0763B0763B0763B0783C0783C0783C0783D07A3D07A3D07A3D07A3D07A3E07C3E07C3E07C3E07C3E" ;
    defparam triglut_1_0_0_0.INITVAL_10 = "0x07C3E07C3F07E3F07E3F07E3F07E3F07E3F07E3F07E3F07E3F07E3F07E3F07E3F07E3F07E3F07E3F" ;
    defparam triglut_1_0_0_0.INITVAL_0F = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_0E = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_0D = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_0C = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_0B = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_0A = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_09 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_08 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_07 = "0x193920B7243DAB62FE48223D91456B066FB3888C2A81C1C9AB0E73A002C831E55239E21516E066F9" ;
    defparam triglut_1_0_0_0.INITVAL_06 = "0x37C8328E0C1A1930AF1A3BA9F2C4241CBA70CF283D0A82D0271CBA40C51F3B8992AA1119987084FC" ;
    defparam triglut_1_0_0_0.INITVAL_05 = "0x36A6E24FDF12F4E008BA2E0251B38D080F334A57211B80D11738C74243CE0F5263A27B249CD0EB1D" ;
    defparam triglut_1_0_0_0.INITVAL_04 = "0x3886A21FB40B0FB33C401C381042C02BDFB1313439E692079B066CA2C1F61151E362431A9643E882" ;
    defparam triglut_1_0_0_0.INITVAL_03 = "0x2219D052B427DC80A0D72BDE40D0EC2DFF10E4F22E3EF0D8E92C9DE0AED028FBD064A72358C3FA6E" ;
    defparam triglut_1_0_0_0.INITVAL_02 = "0x1BB4B3702411EF92C5CA062971F75F38423106E32839E3F45515F082BFB601660167052ADA63E842" ;
    defparam triglut_1_0_0_0.INITVAL_01 = "0x11CD92476C369FB080851910A2958A392060847D16EEF24F5D325C63F22A0B48916EE421F3A2C78A" ;
    defparam triglut_1_0_0_0.INITVAL_00 = "0x363D63F61E07E600FE9D174D61E10A2453829D622EB87331A736BC239DD93C5EA3E3F63F5FE3FFFF" ;
    defparam triglut_1_0_0_0.CSDECODE_B = "0b000" ;
    defparam triglut_1_0_0_0.CSDECODE_A = "0b000" ;
    defparam triglut_1_0_0_0.WRITEMODE_B = "NORMAL" ;
    defparam triglut_1_0_0_0.WRITEMODE_A = "NORMAL" ;
    defparam triglut_1_0_0_0.GSR = "ENABLED" ;
    defparam triglut_1_0_0_0.RESETMODE = "ASYNC" ;
    defparam triglut_1_0_0_0.REGMODE_B = "NOREG" ;
    defparam triglut_1_0_0_0.REGMODE_A = "NOREG" ;
    defparam triglut_1_0_0_0.DATA_WIDTH_B = 9 ;
    defparam triglut_1_0_0_0.DATA_WIDTH_A = 9 ;
    DP8KC triglut_1_0_0_0 (.DIA8(scuba_vlo), .DIA7(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA5(scuba_vlo), .DIA4(scuba_vlo), .DIA3(scuba_vlo), .DIA2(scuba_vlo), 
        .DIA1(scuba_vlo), .DIA0(scuba_vlo), .ADA12(scuba_vlo), .ADA11(scuba_vlo), 
        .ADA10(rom_addr0_r_n_15), .ADA9(rom_addr0_r_n_14), .ADA8(rom_addr0_r_n_13), 
        .ADA7(rom_addr0_r_n_12), .ADA6(rom_addr0_r_n_11), .ADA5(rom_addr0_r_n_10), 
        .ADA4(rom_addr0_r_n_9), .ADA3(rom_addr0_r_n_8), .ADA2(scuba_vlo), 
        .ADA1(scuba_vlo), .ADA0(scuba_vlo), .CEA(ClkEn), .OCEA(ClkEn), .CLKA(Clock), 
        .WEA(scuba_vlo), .CSA2(scuba_vlo), .CSA1(scuba_vlo), .CSA0(scuba_vlo), 
        .RSTA(Reset), .DIB8(scuba_vlo), .DIB7(scuba_vlo), .DIB6(scuba_vlo), 
        .DIB5(scuba_vlo), .DIB4(scuba_vlo), .DIB3(scuba_vlo), .DIB2(scuba_vlo), 
        .DIB1(scuba_vlo), .DIB0(scuba_vlo), .ADB12(scuba_vhi), .ADB11(scuba_vlo), 
        .ADB10(rom_addr0_r_n_15), .ADB9(rom_addr0_r_n_14), .ADB8(rom_addr0_r_n_13), 
        .ADB7(rom_addr0_r_n_12), .ADB6(rom_addr0_r_n_11), .ADB5(rom_addr0_r_n_10), 
        .ADB4(rom_addr0_r_n_9), .ADB3(rom_addr0_r_n_8), .ADB2(scuba_vlo), 
        .ADB1(scuba_vlo), .ADB0(scuba_vlo), .CEB(ClkEn), .OCEB(ClkEn), .CLKB(Clock), 
        .WEB(scuba_vlo), .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), 
        .RSTB(Reset), .DOA8(rom_dout_8), .DOA7(rom_dout_7), .DOA6(rom_dout_6), 
        .DOA5(rom_dout_5), .DOA4(rom_dout_4), .DOA3(rom_dout_3), .DOA2(rom_dout_2), 
        .DOA1(rom_dout_1), .DOA0(rom_dout), .DOB8(), .DOB7(), .DOB6(rom_dout_15), 
        .DOB5(rom_dout_14), .DOB4(rom_dout_13), .DOB3(rom_dout_12), .DOB2(rom_dout_11), 
        .DOB1(rom_dout_10), .DOB0(rom_dout_9))
             /* synthesis MEM_LPC_FILE="sincos.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    FD1P3DX FF_11 (.D(Theta[0]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(Theta[1]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_9 (.D(Theta[2]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_8 (.D(Theta[3]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_7 (.D(Theta[4]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(Theta[5]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(Theta[6]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_6))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(Theta[7]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_7))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(Theta[8]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(mx_ctrl_r))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(Theta[9]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(mx_ctrl_r_1))
             /* synthesis GSR="ENABLED" */;

    MUX21 muxb_39 (.D0(rom_addr0_r_n), .D1(rom_addr0_r), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_8));

    MUX21 muxb_38 (.D0(rom_addr0_r_n_1), .D1(rom_addr0_r_1), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_9));

    MUX21 muxb_37 (.D0(rom_addr0_r_n_2), .D1(rom_addr0_r_2), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_10));

    MUX21 muxb_36 (.D0(rom_addr0_r_n_3), .D1(rom_addr0_r_3), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_11));

    MUX21 muxb_35 (.D0(rom_addr0_r_n_4), .D1(rom_addr0_r_4), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_12));

    MUX21 muxb_34 (.D0(rom_addr0_r_n_5), .D1(rom_addr0_r_5), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_13));

    MUX21 muxb_33 (.D0(rom_addr0_r_n_6), .D1(rom_addr0_r_6), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_14));

    MUX21 muxb_32 (.D0(rom_addr0_r_n_7), .D1(rom_addr0_r_7), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_15));

    FD1P3DX FF_1 (.D(mx_ctrl_r_1), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(sinromoutsel))
             /* synthesis GSR="ENABLED" */;

    MUX21 muxb_31 (.D0(rom_dout), .D1(rom_dout_n), .SD(sinromoutsel), .Z(rom_dout_16));

    MUX21 muxb_30 (.D0(rom_dout_1), .D1(rom_dout_n_1), .SD(sinromoutsel), 
        .Z(rom_dout_17));

    MUX21 muxb_29 (.D0(rom_dout_2), .D1(rom_dout_n_2), .SD(sinromoutsel), 
        .Z(rom_dout_18));

    MUX21 muxb_28 (.D0(rom_dout_3), .D1(rom_dout_n_3), .SD(sinromoutsel), 
        .Z(rom_dout_19));

    MUX21 muxb_27 (.D0(rom_dout_4), .D1(rom_dout_n_4), .SD(sinromoutsel), 
        .Z(rom_dout_20));

    MUX21 muxb_26 (.D0(rom_dout_5), .D1(rom_dout_n_5), .SD(sinromoutsel), 
        .Z(rom_dout_21));

    MUX21 muxb_25 (.D0(rom_dout_6), .D1(rom_dout_n_6), .SD(sinromoutsel), 
        .Z(rom_dout_22));

    MUX21 muxb_24 (.D0(rom_dout_7), .D1(rom_dout_n_7), .SD(sinromoutsel), 
        .Z(rom_dout_23));

    MUX21 muxb_23 (.D0(rom_dout_8), .D1(rom_dout_n_8), .SD(sinromoutsel), 
        .Z(rom_dout_24));

    MUX21 muxb_22 (.D0(rom_dout_9), .D1(rom_dout_n_9), .SD(sinromoutsel), 
        .Z(rom_dout_25));

    MUX21 muxb_21 (.D0(rom_dout_10), .D1(rom_dout_n_10), .SD(sinromoutsel), 
        .Z(rom_dout_26));

    MUX21 muxb_20 (.D0(rom_dout_11), .D1(rom_dout_n_11), .SD(sinromoutsel), 
        .Z(rom_dout_27));

    MUX21 muxb_19 (.D0(rom_dout_12), .D1(rom_dout_n_12), .SD(sinromoutsel), 
        .Z(rom_dout_28));

    MUX21 muxb_18 (.D0(rom_dout_13), .D1(rom_dout_n_13), .SD(sinromoutsel), 
        .Z(rom_dout_29));

    MUX21 muxb_17 (.D0(rom_dout_14), .D1(rom_dout_n_14), .SD(sinromoutsel), 
        .Z(rom_dout_30));

    MUX21 muxb_16 (.D0(rom_dout_15), .D1(rom_dout_n_15), .SD(sinromoutsel), 
        .Z(rom_dout_31));

    FD1P3DX FF_0 (.D(out_sel_i), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(out_sel))
             /* synthesis GSR="ENABLED" */;

    MUX21 muxb_15 (.D0(rom_dout_16), .D1(scuba_vlo), .SD(out_sel), .Z(Sine[0]));

    MUX21 muxb_14 (.D0(rom_dout_17), .D1(scuba_vlo), .SD(out_sel), .Z(Sine[1]));

    MUX21 muxb_13 (.D0(rom_dout_18), .D1(scuba_vlo), .SD(out_sel), .Z(Sine[2]));

    MUX21 muxb_12 (.D0(rom_dout_19), .D1(scuba_vlo), .SD(out_sel), .Z(Sine[3]));

    MUX21 muxb_11 (.D0(rom_dout_20), .D1(scuba_vlo), .SD(out_sel), .Z(Sine[4]));

    MUX21 muxb_10 (.D0(rom_dout_21), .D1(scuba_vlo), .SD(out_sel), .Z(Sine[5]));

    MUX21 muxb_9 (.D0(rom_dout_22), .D1(scuba_vlo), .SD(out_sel), .Z(Sine[6]));

    MUX21 muxb_8 (.D0(rom_dout_23), .D1(scuba_vlo), .SD(out_sel), .Z(Sine[7]));

    MUX21 muxb_7 (.D0(rom_dout_24), .D1(scuba_vlo), .SD(out_sel), .Z(Sine[8]));

    MUX21 muxb_6 (.D0(rom_dout_25), .D1(scuba_vlo), .SD(out_sel), .Z(Sine[9]));

    MUX21 muxb_5 (.D0(rom_dout_26), .D1(scuba_vlo), .SD(out_sel), .Z(Sine[10]));

    MUX21 muxb_4 (.D0(rom_dout_27), .D1(scuba_vlo), .SD(out_sel), .Z(Sine[11]));

    MUX21 muxb_3 (.D0(rom_dout_28), .D1(scuba_vlo), .SD(out_sel), .Z(Sine[12]));

    MUX21 muxb_2 (.D0(rom_dout_29), .D1(scuba_vlo), .SD(out_sel), .Z(Sine[13]));

    MUX21 muxb_1 (.D0(rom_dout_30), .D1(scuba_vlo), .SD(out_sel), .Z(Sine[14]));

    MUX21 muxb_0 (.D0(rom_dout_31), .D1(scuba_vlo), .SD(out_sel), .Z(Sine[15]));

    FADD2B neg_rom_addr0_r_n_0 (.A0(scuba_vlo), .A1(rom_addr0_r_inv), .B0(scuba_vlo), 
        .B1(scuba_vhi), .CI(scuba_vlo), .COUT(co0), .S0(), .S1(rom_addr0_r_n));

    FADD2B neg_rom_addr0_r_n_1 (.A0(rom_addr0_r_1_inv), .A1(rom_addr0_r_2_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co0), .COUT(co1), .S0(rom_addr0_r_n_1), 
        .S1(rom_addr0_r_n_2));

    FADD2B neg_rom_addr0_r_n_2 (.A0(rom_addr0_r_3_inv), .A1(rom_addr0_r_4_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co1), .COUT(co2), .S0(rom_addr0_r_n_3), 
        .S1(rom_addr0_r_n_4));

    FADD2B neg_rom_addr0_r_n_3 (.A0(rom_addr0_r_5_inv), .A1(rom_addr0_r_6_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co2), .COUT(co3), .S0(rom_addr0_r_n_5), 
        .S1(rom_addr0_r_n_6));

    FADD2B neg_rom_addr0_r_n_4 (.A0(rom_addr0_r_7_inv), .A1(scuba_vlo), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co3), .COUT(), .S0(rom_addr0_r_n_7), 
        .S1());

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    FADD2B neg_rom_dout_n_0 (.A0(scuba_vlo), .A1(rom_dout_inv), .B0(scuba_vlo), 
        .B1(scuba_vhi), .CI(scuba_vlo), .COUT(co0_1), .S0(), .S1(rom_dout_n));

    FADD2B neg_rom_dout_n_1 (.A0(rom_dout_1_inv), .A1(rom_dout_2_inv), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co0_1), .COUT(co1_1), .S0(rom_dout_n_1), .S1(rom_dout_n_2));

    FADD2B neg_rom_dout_n_2 (.A0(rom_dout_3_inv), .A1(rom_dout_4_inv), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co1_1), .COUT(co2_1), .S0(rom_dout_n_3), .S1(rom_dout_n_4));

    FADD2B neg_rom_dout_n_3 (.A0(rom_dout_5_inv), .A1(rom_dout_6_inv), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co2_1), .COUT(co3_1), .S0(rom_dout_n_5), .S1(rom_dout_n_6));

    FADD2B neg_rom_dout_n_4 (.A0(rom_dout_7_inv), .A1(rom_dout_8_inv), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co3_1), .COUT(co4), .S0(rom_dout_n_7), .S1(rom_dout_n_8));

    FADD2B neg_rom_dout_n_5 (.A0(rom_dout_9_inv), .A1(rom_dout_10_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co4), .COUT(co5), .S0(rom_dout_n_9), 
        .S1(rom_dout_n_10));

    FADD2B neg_rom_dout_n_6 (.A0(rom_dout_11_inv), .A1(rom_dout_12_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co5), .COUT(co6), .S0(rom_dout_n_11), 
        .S1(rom_dout_n_12));

    FADD2B neg_rom_dout_n_7 (.A0(rom_dout_13_inv), .A1(rom_dout_14_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co6), .COUT(co7), .S0(rom_dout_n_13), 
        .S1(rom_dout_n_14));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    FADD2B neg_rom_dout_n_8 (.A0(rom_dout_15_inv), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co7), .COUT(), .S0(rom_dout_n_15), .S1());



    // exemplar begin
    // exemplar attribute triglut_1_0_0_0 MEM_LPC_FILE sincos.lpc
    // exemplar attribute triglut_1_0_0_0 MEM_INIT_FILE 
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
