/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 4.9 */
/* C:\lscc\diamond\3.8_x64\ispfpga\bin\nt64\scuba.exe -w -n mult -lang verilog -synth synplify -bus_exp 7 -bb -arch xo3c00f -type dspmult -simple_portname -pfu_mult -widtha 16 -widthb 16 -widthp 32 -signed -PL_stages 0  */
/* Sun Jan 29 15:33:05 2017 */


`timescale 1 ns / 1 ps
module mult (DataA, DataB, Result)/* synthesis NGD_DRC_MASK=1 */;
    input wire [15:0] DataA;
    input wire [15:0] DataB;
    output wire [31:0] Result;

    wire mult_0_pp_0_0;
    wire s_mult_0_0_2;
    wire mult_0_pp_1_2;
    wire s_mult_0_0_3;
    wire co_mult_0_0_1;
    wire co_mult_0_0_2;
    wire co_mult_0_0_3;
    wire co_mult_0_0_4;
    wire co_mult_0_0_5;
    wire co_mult_0_0_6;
    wire co_mult_0_0_7;
    wire co_mult_0_0_8;
    wire mult_0_pp_0_17;
    wire co_mult_0_0_9;
    wire mult_0_pp_1_19;
    wire co_mult_0_0_10;
    wire mult_0_pp_3_6;
    wire co_mult_0_1_1;
    wire co_mult_0_1_2;
    wire co_mult_0_1_3;
    wire co_mult_0_1_4;
    wire co_mult_0_1_5;
    wire co_mult_0_1_6;
    wire co_mult_0_1_7;
    wire co_mult_0_1_8;
    wire mult_0_pp_2_21;
    wire co_mult_0_1_9;
    wire mult_0_pp_3_23;
    wire co_mult_0_1_10;
    wire mult_0_pp_5_10;
    wire co_mult_0_2_1;
    wire co_mult_0_2_2;
    wire co_mult_0_2_3;
    wire co_mult_0_2_4;
    wire co_mult_0_2_5;
    wire co_mult_0_2_6;
    wire co_mult_0_2_7;
    wire co_mult_0_2_8;
    wire mult_0_pp_4_25;
    wire co_mult_0_2_9;
    wire mult_0_pp_5_27;
    wire co_mult_0_2_10;
    wire mult_0_pp_7_14;
    wire co_mult_0_3_1;
    wire co_mult_0_3_2;
    wire co_mult_0_3_3;
    wire co_mult_0_3_4;
    wire co_mult_0_3_5;
    wire co_mult_0_3_6;
    wire co_mult_0_3_7;
    wire co_mult_0_3_8;
    wire mult_0_pp_6_29;
    wire co_mult_0_3_10;
    wire co_mult_0_3_9;
    wire mult_0_pp_7_31;
    wire s_mult_0_4_4;
    wire mult_0_pp_2_4;
    wire s_mult_0_0_4;
    wire s_mult_0_4_5;
    wire s_mult_0_4_6;
    wire co_mult_0_4_1;
    wire s_mult_0_1_6;
    wire s_mult_0_0_5;
    wire s_mult_0_0_6;
    wire s_mult_0_4_7;
    wire co_mult_0_4_2;
    wire s_mult_0_1_7;
    wire s_mult_0_1_8;
    wire s_mult_0_0_7;
    wire s_mult_0_0_8;
    wire co_mult_0_4_3;
    wire s_mult_0_1_9;
    wire s_mult_0_1_10;
    wire s_mult_0_0_9;
    wire s_mult_0_0_10;
    wire co_mult_0_4_4;
    wire s_mult_0_1_11;
    wire s_mult_0_1_12;
    wire s_mult_0_0_11;
    wire s_mult_0_0_12;
    wire co_mult_0_4_5;
    wire s_mult_0_1_13;
    wire s_mult_0_1_14;
    wire s_mult_0_0_13;
    wire s_mult_0_0_14;
    wire co_mult_0_4_6;
    wire s_mult_0_1_15;
    wire s_mult_0_1_16;
    wire s_mult_0_0_15;
    wire s_mult_0_0_16;
    wire co_mult_0_4_7;
    wire s_mult_0_1_17;
    wire s_mult_0_1_18;
    wire s_mult_0_0_17;
    wire s_mult_0_0_18;
    wire co_mult_0_4_8;
    wire s_mult_0_1_19;
    wire s_mult_0_1_20;
    wire s_mult_0_0_19;
    wire s_mult_0_0_20;
    wire co_mult_0_4_9;
    wire s_mult_0_1_21;
    wire s_mult_0_1_22;
    wire s_mult_0_0_21;
    wire co_mult_0_4_10;
    wire s_mult_0_1_23;
    wire s_mult_0_1_24;
    wire co_mult_0_4_11;
    wire s_mult_0_1_25;
    wire co_mult_0_4_12;
    wire mult_0_pp_6_12;
    wire s_mult_0_2_12;
    wire co_mult_0_5_1;
    wire s_mult_0_3_14;
    wire s_mult_0_2_13;
    wire s_mult_0_2_14;
    wire co_mult_0_5_2;
    wire s_mult_0_3_15;
    wire s_mult_0_3_16;
    wire s_mult_0_2_15;
    wire s_mult_0_2_16;
    wire co_mult_0_5_3;
    wire s_mult_0_3_17;
    wire s_mult_0_3_18;
    wire s_mult_0_2_17;
    wire s_mult_0_2_18;
    wire co_mult_0_5_4;
    wire s_mult_0_3_19;
    wire s_mult_0_3_20;
    wire s_mult_0_2_19;
    wire s_mult_0_2_20;
    wire co_mult_0_5_5;
    wire s_mult_0_3_21;
    wire s_mult_0_3_22;
    wire s_mult_0_2_21;
    wire s_mult_0_2_22;
    wire co_mult_0_5_6;
    wire s_mult_0_3_23;
    wire s_mult_0_3_24;
    wire s_mult_0_2_23;
    wire s_mult_0_2_24;
    wire co_mult_0_5_7;
    wire s_mult_0_3_25;
    wire s_mult_0_3_26;
    wire s_mult_0_2_25;
    wire s_mult_0_2_26;
    wire co_mult_0_5_8;
    wire s_mult_0_3_27;
    wire s_mult_0_3_28;
    wire s_mult_0_2_27;
    wire s_mult_0_2_28;
    wire co_mult_0_5_9;
    wire s_mult_0_3_29;
    wire s_mult_0_3_30;
    wire s_mult_0_2_29;
    wire co_mult_0_5_11;
    wire co_mult_0_5_10;
    wire s_mult_0_3_31;
    wire mult_0_pp_4_8;
    wire s_mult_0_4_8;
    wire co_t_mult_0_6_1;
    wire s_mult_0_2_10;
    wire s_mult_0_4_9;
    wire s_mult_0_4_10;
    wire co_t_mult_0_6_2;
    wire s_mult_0_2_11;
    wire s_mult_0_5_12;
    wire s_mult_0_4_11;
    wire s_mult_0_4_12;
    wire co_t_mult_0_6_3;
    wire s_mult_0_5_13;
    wire s_mult_0_5_14;
    wire s_mult_0_4_13;
    wire s_mult_0_4_14;
    wire co_t_mult_0_6_4;
    wire s_mult_0_5_15;
    wire s_mult_0_5_16;
    wire s_mult_0_4_15;
    wire s_mult_0_4_16;
    wire co_t_mult_0_6_5;
    wire s_mult_0_5_17;
    wire s_mult_0_5_18;
    wire s_mult_0_4_17;
    wire s_mult_0_4_18;
    wire co_t_mult_0_6_6;
    wire s_mult_0_5_19;
    wire s_mult_0_5_20;
    wire s_mult_0_4_19;
    wire s_mult_0_4_20;
    wire co_t_mult_0_6_7;
    wire s_mult_0_5_21;
    wire s_mult_0_5_22;
    wire s_mult_0_4_21;
    wire s_mult_0_4_22;
    wire co_t_mult_0_6_8;
    wire s_mult_0_5_23;
    wire s_mult_0_5_24;
    wire s_mult_0_4_23;
    wire s_mult_0_4_24;
    wire co_t_mult_0_6_9;
    wire s_mult_0_5_25;
    wire s_mult_0_5_26;
    wire s_mult_0_4_25;
    wire s_mult_0_4_26;
    wire co_t_mult_0_6_10;
    wire s_mult_0_5_27;
    wire s_mult_0_5_28;
    wire s_mult_0_4_27;
    wire co_t_mult_0_6_11;
    wire s_mult_0_5_29;
    wire s_mult_0_5_30;
    wire co_t_mult_0_6_13;
    wire co_t_mult_0_6_12;
    wire s_mult_0_5_31;
    wire mult_0_pp_0_2;
    wire mult_0_pp_0_1;
    wire mult_0_cin_lr_0;
    wire mult_0_pp_0_4;
    wire mult_0_pp_0_3;
    wire mco;
    wire mult_0_pp_0_6;
    wire mult_0_pp_0_5;
    wire mco_1;
    wire mult_0_pp_0_8;
    wire mult_0_pp_0_7;
    wire mco_2;
    wire mult_0_pp_0_10;
    wire mult_0_pp_0_9;
    wire mco_3;
    wire mult_0_pp_0_12;
    wire mult_0_pp_0_11;
    wire mco_4;
    wire mult_0_pp_0_14;
    wire mult_0_pp_0_13;
    wire mco_5;
    wire mfco;
    wire mult_0_pp_0_16;
    wire mult_0_pp_0_15;
    wire mco_6;
    wire mult_0_mult_0_7_n1;
    wire mult_0_mult_0_7_n2;
    wire mult_0_pp_1_4;
    wire mult_0_pp_1_3;
    wire mult_0_cin_lr_2;
    wire mult_0_pp_1_6;
    wire mult_0_pp_1_5;
    wire mco_7;
    wire mult_0_pp_1_8;
    wire mult_0_pp_1_7;
    wire mco_8;
    wire mult_0_pp_1_10;
    wire mult_0_pp_1_9;
    wire mco_9;
    wire mult_0_pp_1_12;
    wire mult_0_pp_1_11;
    wire mco_10;
    wire mult_0_pp_1_14;
    wire mult_0_pp_1_13;
    wire mco_11;
    wire mult_0_pp_1_16;
    wire mult_0_pp_1_15;
    wire mco_12;
    wire mfco_1;
    wire mult_0_pp_1_18;
    wire mult_0_pp_1_17;
    wire mco_13;
    wire mult_0_mult_2_7_n1;
    wire mult_0_mult_2_7_n2;
    wire mult_0_pp_2_6;
    wire mult_0_pp_2_5;
    wire mult_0_cin_lr_4;
    wire mult_0_pp_2_8;
    wire mult_0_pp_2_7;
    wire mco_14;
    wire mult_0_pp_2_10;
    wire mult_0_pp_2_9;
    wire mco_15;
    wire mult_0_pp_2_12;
    wire mult_0_pp_2_11;
    wire mco_16;
    wire mult_0_pp_2_14;
    wire mult_0_pp_2_13;
    wire mco_17;
    wire mult_0_pp_2_16;
    wire mult_0_pp_2_15;
    wire mco_18;
    wire mult_0_pp_2_18;
    wire mult_0_pp_2_17;
    wire mco_19;
    wire mfco_2;
    wire mult_0_pp_2_20;
    wire mult_0_pp_2_19;
    wire mco_20;
    wire mult_0_mult_4_7_n1;
    wire mult_0_mult_4_7_n2;
    wire mult_0_pp_3_8;
    wire mult_0_pp_3_7;
    wire mult_0_cin_lr_6;
    wire mult_0_pp_3_10;
    wire mult_0_pp_3_9;
    wire mco_21;
    wire mult_0_pp_3_12;
    wire mult_0_pp_3_11;
    wire mco_22;
    wire mult_0_pp_3_14;
    wire mult_0_pp_3_13;
    wire mco_23;
    wire mult_0_pp_3_16;
    wire mult_0_pp_3_15;
    wire mco_24;
    wire mult_0_pp_3_18;
    wire mult_0_pp_3_17;
    wire mco_25;
    wire mult_0_pp_3_20;
    wire mult_0_pp_3_19;
    wire mco_26;
    wire mfco_3;
    wire mult_0_pp_3_22;
    wire mult_0_pp_3_21;
    wire mco_27;
    wire mult_0_mult_6_7_n1;
    wire mult_0_mult_6_7_n2;
    wire mult_0_pp_4_10;
    wire mult_0_pp_4_9;
    wire mult_0_cin_lr_8;
    wire mult_0_pp_4_12;
    wire mult_0_pp_4_11;
    wire mco_28;
    wire mult_0_pp_4_14;
    wire mult_0_pp_4_13;
    wire mco_29;
    wire mult_0_pp_4_16;
    wire mult_0_pp_4_15;
    wire mco_30;
    wire mult_0_pp_4_18;
    wire mult_0_pp_4_17;
    wire mco_31;
    wire mult_0_pp_4_20;
    wire mult_0_pp_4_19;
    wire mco_32;
    wire mult_0_pp_4_22;
    wire mult_0_pp_4_21;
    wire mco_33;
    wire mfco_4;
    wire mult_0_pp_4_24;
    wire mult_0_pp_4_23;
    wire mco_34;
    wire mult_0_mult_8_7_n1;
    wire mult_0_mult_8_7_n2;
    wire mult_0_pp_5_12;
    wire mult_0_pp_5_11;
    wire mult_0_cin_lr_10;
    wire mult_0_pp_5_14;
    wire mult_0_pp_5_13;
    wire mco_35;
    wire mult_0_pp_5_16;
    wire mult_0_pp_5_15;
    wire mco_36;
    wire mult_0_pp_5_18;
    wire mult_0_pp_5_17;
    wire mco_37;
    wire mult_0_pp_5_20;
    wire mult_0_pp_5_19;
    wire mco_38;
    wire mult_0_pp_5_22;
    wire mult_0_pp_5_21;
    wire mco_39;
    wire mult_0_pp_5_24;
    wire mult_0_pp_5_23;
    wire mco_40;
    wire mfco_5;
    wire mult_0_pp_5_26;
    wire mult_0_pp_5_25;
    wire mco_41;
    wire mult_0_mult_10_7_n1;
    wire mult_0_mult_10_7_n2;
    wire mult_0_pp_6_14;
    wire mult_0_pp_6_13;
    wire mult_0_cin_lr_12;
    wire mult_0_pp_6_16;
    wire mult_0_pp_6_15;
    wire mco_42;
    wire mult_0_pp_6_18;
    wire mult_0_pp_6_17;
    wire mco_43;
    wire mult_0_pp_6_20;
    wire mult_0_pp_6_19;
    wire mco_44;
    wire mult_0_pp_6_22;
    wire mult_0_pp_6_21;
    wire mco_45;
    wire mult_0_pp_6_24;
    wire mult_0_pp_6_23;
    wire mco_46;
    wire mult_0_pp_6_26;
    wire mult_0_pp_6_25;
    wire mco_47;
    wire mfco_6;
    wire mult_0_pp_6_28;
    wire mult_0_pp_6_27;
    wire mco_48;
    wire mult_0_mult_12_7_n1;
    wire mult_0_mult_12_7_n2;
    wire mult_0_pp_7_16;
    wire mult_0_pp_7_15;
    wire mult_0_cin_lr_14;
    wire mult_0_mult_14_0_n1;
    wire mult_0_mult_14_0_n0;
    wire mult_0_pp_7_18;
    wire mult_0_pp_7_17;
    wire mco_49;
    wire mult_0_mult_14_1_n1;
    wire mult_0_mult_14_1_n0;
    wire mult_0_pp_7_20;
    wire mult_0_pp_7_19;
    wire mco_50;
    wire mult_0_mult_14_2_n1;
    wire mult_0_mult_14_2_n0;
    wire mult_0_pp_7_22;
    wire mult_0_pp_7_21;
    wire mco_51;
    wire mult_0_mult_14_3_n1;
    wire mult_0_mult_14_3_n0;
    wire mult_0_pp_7_24;
    wire mult_0_pp_7_23;
    wire mco_52;
    wire mult_0_mult_14_4_n1;
    wire mult_0_mult_14_4_n0;
    wire mult_0_pp_7_26;
    wire mult_0_pp_7_25;
    wire mco_53;
    wire mult_0_mult_14_5_n1;
    wire mult_0_mult_14_5_n0;
    wire mult_0_pp_7_28;
    wire mult_0_pp_7_27;
    wire mco_54;
    wire mult_0_mult_14_6_n1;
    wire mult_0_mult_14_6_n0;
    wire mfco_7;
    wire mult_0_pp_7_30;
    wire mult_0_pp_7_29;
    wire mco_55;
    wire scuba_vlo;
    wire mult_0_mult_14_7_n2;
    wire scuba_vhi;
    wire mult_0_mult_14_7_n0;

    AND2 AND2_t37 (.A(DataA[0]), .B(DataB[0]), .Z(mult_0_pp_0_0));

    ND2 ND2_t36 (.A(DataA[15]), .B(DataB[0]), .Z(mult_0_mult_0_7_n2));

    ND2 ND2_t35 (.A(DataA[15]), .B(DataB[1]), .Z(mult_0_mult_0_7_n1));

    AND2 AND2_t34 (.A(DataA[0]), .B(DataB[2]), .Z(mult_0_pp_1_2));

    ND2 ND2_t33 (.A(DataA[15]), .B(DataB[2]), .Z(mult_0_mult_2_7_n2));

    ND2 ND2_t32 (.A(DataA[15]), .B(DataB[3]), .Z(mult_0_mult_2_7_n1));

    AND2 AND2_t31 (.A(DataA[0]), .B(DataB[4]), .Z(mult_0_pp_2_4));

    ND2 ND2_t30 (.A(DataA[15]), .B(DataB[4]), .Z(mult_0_mult_4_7_n2));

    ND2 ND2_t29 (.A(DataA[15]), .B(DataB[5]), .Z(mult_0_mult_4_7_n1));

    AND2 AND2_t28 (.A(DataA[0]), .B(DataB[6]), .Z(mult_0_pp_3_6));

    ND2 ND2_t27 (.A(DataA[15]), .B(DataB[6]), .Z(mult_0_mult_6_7_n2));

    ND2 ND2_t26 (.A(DataA[15]), .B(DataB[7]), .Z(mult_0_mult_6_7_n1));

    AND2 AND2_t25 (.A(DataA[0]), .B(DataB[8]), .Z(mult_0_pp_4_8));

    ND2 ND2_t24 (.A(DataA[15]), .B(DataB[8]), .Z(mult_0_mult_8_7_n2));

    ND2 ND2_t23 (.A(DataA[15]), .B(DataB[9]), .Z(mult_0_mult_8_7_n1));

    AND2 AND2_t22 (.A(DataA[0]), .B(DataB[10]), .Z(mult_0_pp_5_10));

    ND2 ND2_t21 (.A(DataA[15]), .B(DataB[10]), .Z(mult_0_mult_10_7_n2));

    ND2 ND2_t20 (.A(DataA[15]), .B(DataB[11]), .Z(mult_0_mult_10_7_n1));

    AND2 AND2_t19 (.A(DataA[0]), .B(DataB[12]), .Z(mult_0_pp_6_12));

    ND2 ND2_t18 (.A(DataA[15]), .B(DataB[12]), .Z(mult_0_mult_12_7_n2));

    ND2 ND2_t17 (.A(DataA[15]), .B(DataB[13]), .Z(mult_0_mult_12_7_n1));

    AND2 AND2_t16 (.A(DataA[0]), .B(DataB[14]), .Z(mult_0_pp_7_14));

    ND2 ND2_t15 (.A(DataA[1]), .B(DataB[15]), .Z(mult_0_mult_14_0_n1));

    ND2 ND2_t14 (.A(DataA[0]), .B(DataB[15]), .Z(mult_0_mult_14_0_n0));

    ND2 ND2_t13 (.A(DataA[3]), .B(DataB[15]), .Z(mult_0_mult_14_1_n1));

    ND2 ND2_t12 (.A(DataA[2]), .B(DataB[15]), .Z(mult_0_mult_14_1_n0));

    ND2 ND2_t11 (.A(DataA[5]), .B(DataB[15]), .Z(mult_0_mult_14_2_n1));

    ND2 ND2_t10 (.A(DataA[4]), .B(DataB[15]), .Z(mult_0_mult_14_2_n0));

    ND2 ND2_t9 (.A(DataA[7]), .B(DataB[15]), .Z(mult_0_mult_14_3_n1));

    ND2 ND2_t8 (.A(DataA[6]), .B(DataB[15]), .Z(mult_0_mult_14_3_n0));

    ND2 ND2_t7 (.A(DataA[9]), .B(DataB[15]), .Z(mult_0_mult_14_4_n1));

    ND2 ND2_t6 (.A(DataA[8]), .B(DataB[15]), .Z(mult_0_mult_14_4_n0));

    ND2 ND2_t5 (.A(DataA[11]), .B(DataB[15]), .Z(mult_0_mult_14_5_n1));

    ND2 ND2_t4 (.A(DataA[10]), .B(DataB[15]), .Z(mult_0_mult_14_5_n0));

    ND2 ND2_t3 (.A(DataA[13]), .B(DataB[15]), .Z(mult_0_mult_14_6_n1));

    ND2 ND2_t2 (.A(DataA[12]), .B(DataB[15]), .Z(mult_0_mult_14_6_n0));

    ND2 ND2_t1 (.A(DataA[15]), .B(DataB[14]), .Z(mult_0_mult_14_7_n2));

    ND2 ND2_t0 (.A(DataA[14]), .B(DataB[15]), .Z(mult_0_mult_14_7_n0));

    FADD2B mult_0_cin_lr_add_0 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(mult_0_cin_lr_0), .S0(), .S1());

    FADD2B mult_0_Cadd_0_8 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(mfco), .COUT(), .S0(mult_0_pp_0_17), .S1());

    FADD2B mult_0_cin_lr_add_2 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(mult_0_cin_lr_2), .S0(), .S1());

    FADD2B mult_0_Cadd_2_8 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(mfco_1), .COUT(), .S0(mult_0_pp_1_19), .S1());

    FADD2B mult_0_cin_lr_add_4 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(mult_0_cin_lr_4), .S0(), .S1());

    FADD2B mult_0_Cadd_4_8 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(mfco_2), .COUT(), .S0(mult_0_pp_2_21), .S1());

    FADD2B mult_0_cin_lr_add_6 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(mult_0_cin_lr_6), .S0(), .S1());

    FADD2B mult_0_Cadd_6_8 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(mfco_3), .COUT(), .S0(mult_0_pp_3_23), .S1());

    FADD2B mult_0_cin_lr_add_8 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(mult_0_cin_lr_8), .S0(), .S1());

    FADD2B mult_0_Cadd_8_8 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(mfco_4), .COUT(), .S0(mult_0_pp_4_25), .S1());

    FADD2B mult_0_cin_lr_add_10 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(mult_0_cin_lr_10), .S0(), 
        .S1());

    FADD2B mult_0_Cadd_10_8 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(mfco_5), .COUT(), .S0(mult_0_pp_5_27), .S1());

    FADD2B mult_0_cin_lr_add_12 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(mult_0_cin_lr_12), .S0(), 
        .S1());

    FADD2B mult_0_Cadd_12_8 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(mfco_6), .COUT(), .S0(mult_0_pp_6_29), .S1());

    FADD2B mult_0_cin_lr_add_14 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(mult_0_cin_lr_14), .S0(), 
        .S1());

    FADD2B mult_0_Cadd_14_8 (.A0(scuba_vhi), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(mfco_7), .COUT(), .S0(mult_0_pp_7_31), .S1());

    FADD2B Cadd_mult_0_0_1 (.A0(scuba_vlo), .A1(mult_0_pp_0_2), .B0(scuba_vlo), 
        .B1(mult_0_pp_1_2), .CI(scuba_vlo), .COUT(co_mult_0_0_1), .S0(), 
        .S1(s_mult_0_0_2));

    FADD2B mult_0_add_0_2 (.A0(mult_0_pp_0_3), .A1(mult_0_pp_0_4), .B0(mult_0_pp_1_3), 
        .B1(mult_0_pp_1_4), .CI(co_mult_0_0_1), .COUT(co_mult_0_0_2), .S0(s_mult_0_0_3), 
        .S1(s_mult_0_0_4));

    FADD2B mult_0_add_0_3 (.A0(mult_0_pp_0_5), .A1(mult_0_pp_0_6), .B0(mult_0_pp_1_5), 
        .B1(mult_0_pp_1_6), .CI(co_mult_0_0_2), .COUT(co_mult_0_0_3), .S0(s_mult_0_0_5), 
        .S1(s_mult_0_0_6));

    FADD2B mult_0_add_0_4 (.A0(mult_0_pp_0_7), .A1(mult_0_pp_0_8), .B0(mult_0_pp_1_7), 
        .B1(mult_0_pp_1_8), .CI(co_mult_0_0_3), .COUT(co_mult_0_0_4), .S0(s_mult_0_0_7), 
        .S1(s_mult_0_0_8));

    FADD2B mult_0_add_0_5 (.A0(mult_0_pp_0_9), .A1(mult_0_pp_0_10), .B0(mult_0_pp_1_9), 
        .B1(mult_0_pp_1_10), .CI(co_mult_0_0_4), .COUT(co_mult_0_0_5), .S0(s_mult_0_0_9), 
        .S1(s_mult_0_0_10));

    FADD2B mult_0_add_0_6 (.A0(mult_0_pp_0_11), .A1(mult_0_pp_0_12), .B0(mult_0_pp_1_11), 
        .B1(mult_0_pp_1_12), .CI(co_mult_0_0_5), .COUT(co_mult_0_0_6), .S0(s_mult_0_0_11), 
        .S1(s_mult_0_0_12));

    FADD2B mult_0_add_0_7 (.A0(mult_0_pp_0_13), .A1(mult_0_pp_0_14), .B0(mult_0_pp_1_13), 
        .B1(mult_0_pp_1_14), .CI(co_mult_0_0_6), .COUT(co_mult_0_0_7), .S0(s_mult_0_0_13), 
        .S1(s_mult_0_0_14));

    FADD2B mult_0_add_0_8 (.A0(mult_0_pp_0_15), .A1(mult_0_pp_0_16), .B0(mult_0_pp_1_15), 
        .B1(mult_0_pp_1_16), .CI(co_mult_0_0_7), .COUT(co_mult_0_0_8), .S0(s_mult_0_0_15), 
        .S1(s_mult_0_0_16));

    FADD2B mult_0_add_0_9 (.A0(mult_0_pp_0_17), .A1(scuba_vlo), .B0(mult_0_pp_1_17), 
        .B1(mult_0_pp_1_18), .CI(co_mult_0_0_8), .COUT(co_mult_0_0_9), .S0(s_mult_0_0_17), 
        .S1(s_mult_0_0_18));

    FADD2B mult_0_add_0_10 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(mult_0_pp_1_19), 
        .B1(scuba_vlo), .CI(co_mult_0_0_9), .COUT(co_mult_0_0_10), .S0(s_mult_0_0_19), 
        .S1(s_mult_0_0_20));

    FADD2B Cadd_mult_0_0_11 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co_mult_0_0_10), .COUT(), .S0(s_mult_0_0_21), 
        .S1());

    FADD2B Cadd_mult_0_1_1 (.A0(scuba_vlo), .A1(mult_0_pp_2_6), .B0(scuba_vlo), 
        .B1(mult_0_pp_3_6), .CI(scuba_vlo), .COUT(co_mult_0_1_1), .S0(), 
        .S1(s_mult_0_1_6));

    FADD2B mult_0_add_1_2 (.A0(mult_0_pp_2_7), .A1(mult_0_pp_2_8), .B0(mult_0_pp_3_7), 
        .B1(mult_0_pp_3_8), .CI(co_mult_0_1_1), .COUT(co_mult_0_1_2), .S0(s_mult_0_1_7), 
        .S1(s_mult_0_1_8));

    FADD2B mult_0_add_1_3 (.A0(mult_0_pp_2_9), .A1(mult_0_pp_2_10), .B0(mult_0_pp_3_9), 
        .B1(mult_0_pp_3_10), .CI(co_mult_0_1_2), .COUT(co_mult_0_1_3), .S0(s_mult_0_1_9), 
        .S1(s_mult_0_1_10));

    FADD2B mult_0_add_1_4 (.A0(mult_0_pp_2_11), .A1(mult_0_pp_2_12), .B0(mult_0_pp_3_11), 
        .B1(mult_0_pp_3_12), .CI(co_mult_0_1_3), .COUT(co_mult_0_1_4), .S0(s_mult_0_1_11), 
        .S1(s_mult_0_1_12));

    FADD2B mult_0_add_1_5 (.A0(mult_0_pp_2_13), .A1(mult_0_pp_2_14), .B0(mult_0_pp_3_13), 
        .B1(mult_0_pp_3_14), .CI(co_mult_0_1_4), .COUT(co_mult_0_1_5), .S0(s_mult_0_1_13), 
        .S1(s_mult_0_1_14));

    FADD2B mult_0_add_1_6 (.A0(mult_0_pp_2_15), .A1(mult_0_pp_2_16), .B0(mult_0_pp_3_15), 
        .B1(mult_0_pp_3_16), .CI(co_mult_0_1_5), .COUT(co_mult_0_1_6), .S0(s_mult_0_1_15), 
        .S1(s_mult_0_1_16));

    FADD2B mult_0_add_1_7 (.A0(mult_0_pp_2_17), .A1(mult_0_pp_2_18), .B0(mult_0_pp_3_17), 
        .B1(mult_0_pp_3_18), .CI(co_mult_0_1_6), .COUT(co_mult_0_1_7), .S0(s_mult_0_1_17), 
        .S1(s_mult_0_1_18));

    FADD2B mult_0_add_1_8 (.A0(mult_0_pp_2_19), .A1(mult_0_pp_2_20), .B0(mult_0_pp_3_19), 
        .B1(mult_0_pp_3_20), .CI(co_mult_0_1_7), .COUT(co_mult_0_1_8), .S0(s_mult_0_1_19), 
        .S1(s_mult_0_1_20));

    FADD2B mult_0_add_1_9 (.A0(mult_0_pp_2_21), .A1(scuba_vlo), .B0(mult_0_pp_3_21), 
        .B1(mult_0_pp_3_22), .CI(co_mult_0_1_8), .COUT(co_mult_0_1_9), .S0(s_mult_0_1_21), 
        .S1(s_mult_0_1_22));

    FADD2B mult_0_add_1_10 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(mult_0_pp_3_23), 
        .B1(scuba_vlo), .CI(co_mult_0_1_9), .COUT(co_mult_0_1_10), .S0(s_mult_0_1_23), 
        .S1(s_mult_0_1_24));

    FADD2B Cadd_mult_0_1_11 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co_mult_0_1_10), .COUT(), .S0(s_mult_0_1_25), 
        .S1());

    FADD2B Cadd_mult_0_2_1 (.A0(scuba_vlo), .A1(mult_0_pp_4_10), .B0(scuba_vlo), 
        .B1(mult_0_pp_5_10), .CI(scuba_vlo), .COUT(co_mult_0_2_1), .S0(), 
        .S1(s_mult_0_2_10));

    FADD2B mult_0_add_2_2 (.A0(mult_0_pp_4_11), .A1(mult_0_pp_4_12), .B0(mult_0_pp_5_11), 
        .B1(mult_0_pp_5_12), .CI(co_mult_0_2_1), .COUT(co_mult_0_2_2), .S0(s_mult_0_2_11), 
        .S1(s_mult_0_2_12));

    FADD2B mult_0_add_2_3 (.A0(mult_0_pp_4_13), .A1(mult_0_pp_4_14), .B0(mult_0_pp_5_13), 
        .B1(mult_0_pp_5_14), .CI(co_mult_0_2_2), .COUT(co_mult_0_2_3), .S0(s_mult_0_2_13), 
        .S1(s_mult_0_2_14));

    FADD2B mult_0_add_2_4 (.A0(mult_0_pp_4_15), .A1(mult_0_pp_4_16), .B0(mult_0_pp_5_15), 
        .B1(mult_0_pp_5_16), .CI(co_mult_0_2_3), .COUT(co_mult_0_2_4), .S0(s_mult_0_2_15), 
        .S1(s_mult_0_2_16));

    FADD2B mult_0_add_2_5 (.A0(mult_0_pp_4_17), .A1(mult_0_pp_4_18), .B0(mult_0_pp_5_17), 
        .B1(mult_0_pp_5_18), .CI(co_mult_0_2_4), .COUT(co_mult_0_2_5), .S0(s_mult_0_2_17), 
        .S1(s_mult_0_2_18));

    FADD2B mult_0_add_2_6 (.A0(mult_0_pp_4_19), .A1(mult_0_pp_4_20), .B0(mult_0_pp_5_19), 
        .B1(mult_0_pp_5_20), .CI(co_mult_0_2_5), .COUT(co_mult_0_2_6), .S0(s_mult_0_2_19), 
        .S1(s_mult_0_2_20));

    FADD2B mult_0_add_2_7 (.A0(mult_0_pp_4_21), .A1(mult_0_pp_4_22), .B0(mult_0_pp_5_21), 
        .B1(mult_0_pp_5_22), .CI(co_mult_0_2_6), .COUT(co_mult_0_2_7), .S0(s_mult_0_2_21), 
        .S1(s_mult_0_2_22));

    FADD2B mult_0_add_2_8 (.A0(mult_0_pp_4_23), .A1(mult_0_pp_4_24), .B0(mult_0_pp_5_23), 
        .B1(mult_0_pp_5_24), .CI(co_mult_0_2_7), .COUT(co_mult_0_2_8), .S0(s_mult_0_2_23), 
        .S1(s_mult_0_2_24));

    FADD2B mult_0_add_2_9 (.A0(mult_0_pp_4_25), .A1(scuba_vlo), .B0(mult_0_pp_5_25), 
        .B1(mult_0_pp_5_26), .CI(co_mult_0_2_8), .COUT(co_mult_0_2_9), .S0(s_mult_0_2_25), 
        .S1(s_mult_0_2_26));

    FADD2B mult_0_add_2_10 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(mult_0_pp_5_27), 
        .B1(scuba_vlo), .CI(co_mult_0_2_9), .COUT(co_mult_0_2_10), .S0(s_mult_0_2_27), 
        .S1(s_mult_0_2_28));

    FADD2B Cadd_mult_0_2_11 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co_mult_0_2_10), .COUT(), .S0(s_mult_0_2_29), 
        .S1());

    FADD2B Cadd_mult_0_3_1 (.A0(scuba_vlo), .A1(mult_0_pp_6_14), .B0(scuba_vlo), 
        .B1(mult_0_pp_7_14), .CI(scuba_vlo), .COUT(co_mult_0_3_1), .S0(), 
        .S1(s_mult_0_3_14));

    FADD2B mult_0_add_3_2 (.A0(mult_0_pp_6_15), .A1(mult_0_pp_6_16), .B0(mult_0_pp_7_15), 
        .B1(mult_0_pp_7_16), .CI(co_mult_0_3_1), .COUT(co_mult_0_3_2), .S0(s_mult_0_3_15), 
        .S1(s_mult_0_3_16));

    FADD2B mult_0_add_3_3 (.A0(mult_0_pp_6_17), .A1(mult_0_pp_6_18), .B0(mult_0_pp_7_17), 
        .B1(mult_0_pp_7_18), .CI(co_mult_0_3_2), .COUT(co_mult_0_3_3), .S0(s_mult_0_3_17), 
        .S1(s_mult_0_3_18));

    FADD2B mult_0_add_3_4 (.A0(mult_0_pp_6_19), .A1(mult_0_pp_6_20), .B0(mult_0_pp_7_19), 
        .B1(mult_0_pp_7_20), .CI(co_mult_0_3_3), .COUT(co_mult_0_3_4), .S0(s_mult_0_3_19), 
        .S1(s_mult_0_3_20));

    FADD2B mult_0_add_3_5 (.A0(mult_0_pp_6_21), .A1(mult_0_pp_6_22), .B0(mult_0_pp_7_21), 
        .B1(mult_0_pp_7_22), .CI(co_mult_0_3_4), .COUT(co_mult_0_3_5), .S0(s_mult_0_3_21), 
        .S1(s_mult_0_3_22));

    FADD2B mult_0_add_3_6 (.A0(mult_0_pp_6_23), .A1(mult_0_pp_6_24), .B0(mult_0_pp_7_23), 
        .B1(mult_0_pp_7_24), .CI(co_mult_0_3_5), .COUT(co_mult_0_3_6), .S0(s_mult_0_3_23), 
        .S1(s_mult_0_3_24));

    FADD2B mult_0_add_3_7 (.A0(mult_0_pp_6_25), .A1(mult_0_pp_6_26), .B0(mult_0_pp_7_25), 
        .B1(mult_0_pp_7_26), .CI(co_mult_0_3_6), .COUT(co_mult_0_3_7), .S0(s_mult_0_3_25), 
        .S1(s_mult_0_3_26));

    FADD2B mult_0_add_3_8 (.A0(mult_0_pp_6_27), .A1(mult_0_pp_6_28), .B0(mult_0_pp_7_27), 
        .B1(mult_0_pp_7_28), .CI(co_mult_0_3_7), .COUT(co_mult_0_3_8), .S0(s_mult_0_3_27), 
        .S1(s_mult_0_3_28));

    FADD2B mult_0_add_3_9 (.A0(mult_0_pp_6_29), .A1(scuba_vlo), .B0(mult_0_pp_7_29), 
        .B1(mult_0_pp_7_30), .CI(co_mult_0_3_8), .COUT(co_mult_0_3_9), .S0(s_mult_0_3_29), 
        .S1(s_mult_0_3_30));

    FADD2B mult_0_add_3_10 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(mult_0_pp_7_31), 
        .B1(scuba_vlo), .CI(co_mult_0_3_9), .COUT(co_mult_0_3_10), .S0(s_mult_0_3_31), 
        .S1());

    FADD2B Cadd_mult_0_4_1 (.A0(scuba_vlo), .A1(s_mult_0_0_4), .B0(scuba_vlo), 
        .B1(mult_0_pp_2_4), .CI(scuba_vlo), .COUT(co_mult_0_4_1), .S0(), 
        .S1(s_mult_0_4_4));

    FADD2B mult_0_add_4_2 (.A0(s_mult_0_0_5), .A1(s_mult_0_0_6), .B0(mult_0_pp_2_5), 
        .B1(s_mult_0_1_6), .CI(co_mult_0_4_1), .COUT(co_mult_0_4_2), .S0(s_mult_0_4_5), 
        .S1(s_mult_0_4_6));

    FADD2B mult_0_add_4_3 (.A0(s_mult_0_0_7), .A1(s_mult_0_0_8), .B0(s_mult_0_1_7), 
        .B1(s_mult_0_1_8), .CI(co_mult_0_4_2), .COUT(co_mult_0_4_3), .S0(s_mult_0_4_7), 
        .S1(s_mult_0_4_8));

    FADD2B mult_0_add_4_4 (.A0(s_mult_0_0_9), .A1(s_mult_0_0_10), .B0(s_mult_0_1_9), 
        .B1(s_mult_0_1_10), .CI(co_mult_0_4_3), .COUT(co_mult_0_4_4), .S0(s_mult_0_4_9), 
        .S1(s_mult_0_4_10));

    FADD2B mult_0_add_4_5 (.A0(s_mult_0_0_11), .A1(s_mult_0_0_12), .B0(s_mult_0_1_11), 
        .B1(s_mult_0_1_12), .CI(co_mult_0_4_4), .COUT(co_mult_0_4_5), .S0(s_mult_0_4_11), 
        .S1(s_mult_0_4_12));

    FADD2B mult_0_add_4_6 (.A0(s_mult_0_0_13), .A1(s_mult_0_0_14), .B0(s_mult_0_1_13), 
        .B1(s_mult_0_1_14), .CI(co_mult_0_4_5), .COUT(co_mult_0_4_6), .S0(s_mult_0_4_13), 
        .S1(s_mult_0_4_14));

    FADD2B mult_0_add_4_7 (.A0(s_mult_0_0_15), .A1(s_mult_0_0_16), .B0(s_mult_0_1_15), 
        .B1(s_mult_0_1_16), .CI(co_mult_0_4_6), .COUT(co_mult_0_4_7), .S0(s_mult_0_4_15), 
        .S1(s_mult_0_4_16));

    FADD2B mult_0_add_4_8 (.A0(s_mult_0_0_17), .A1(s_mult_0_0_18), .B0(s_mult_0_1_17), 
        .B1(s_mult_0_1_18), .CI(co_mult_0_4_7), .COUT(co_mult_0_4_8), .S0(s_mult_0_4_17), 
        .S1(s_mult_0_4_18));

    FADD2B mult_0_add_4_9 (.A0(s_mult_0_0_19), .A1(s_mult_0_0_20), .B0(s_mult_0_1_19), 
        .B1(s_mult_0_1_20), .CI(co_mult_0_4_8), .COUT(co_mult_0_4_9), .S0(s_mult_0_4_19), 
        .S1(s_mult_0_4_20));

    FADD2B mult_0_add_4_10 (.A0(s_mult_0_0_21), .A1(scuba_vlo), .B0(s_mult_0_1_21), 
        .B1(s_mult_0_1_22), .CI(co_mult_0_4_9), .COUT(co_mult_0_4_10), .S0(s_mult_0_4_21), 
        .S1(s_mult_0_4_22));

    FADD2B mult_0_add_4_11 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(s_mult_0_1_23), 
        .B1(s_mult_0_1_24), .CI(co_mult_0_4_10), .COUT(co_mult_0_4_11), 
        .S0(s_mult_0_4_23), .S1(s_mult_0_4_24));

    FADD2B mult_0_add_4_12 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(s_mult_0_1_25), 
        .B1(scuba_vlo), .CI(co_mult_0_4_11), .COUT(co_mult_0_4_12), .S0(s_mult_0_4_25), 
        .S1(s_mult_0_4_26));

    FADD2B Cadd_mult_0_4_13 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co_mult_0_4_12), .COUT(), .S0(s_mult_0_4_27), 
        .S1());

    FADD2B Cadd_mult_0_5_1 (.A0(scuba_vlo), .A1(s_mult_0_2_12), .B0(scuba_vlo), 
        .B1(mult_0_pp_6_12), .CI(scuba_vlo), .COUT(co_mult_0_5_1), .S0(), 
        .S1(s_mult_0_5_12));

    FADD2B mult_0_add_5_2 (.A0(s_mult_0_2_13), .A1(s_mult_0_2_14), .B0(mult_0_pp_6_13), 
        .B1(s_mult_0_3_14), .CI(co_mult_0_5_1), .COUT(co_mult_0_5_2), .S0(s_mult_0_5_13), 
        .S1(s_mult_0_5_14));

    FADD2B mult_0_add_5_3 (.A0(s_mult_0_2_15), .A1(s_mult_0_2_16), .B0(s_mult_0_3_15), 
        .B1(s_mult_0_3_16), .CI(co_mult_0_5_2), .COUT(co_mult_0_5_3), .S0(s_mult_0_5_15), 
        .S1(s_mult_0_5_16));

    FADD2B mult_0_add_5_4 (.A0(s_mult_0_2_17), .A1(s_mult_0_2_18), .B0(s_mult_0_3_17), 
        .B1(s_mult_0_3_18), .CI(co_mult_0_5_3), .COUT(co_mult_0_5_4), .S0(s_mult_0_5_17), 
        .S1(s_mult_0_5_18));

    FADD2B mult_0_add_5_5 (.A0(s_mult_0_2_19), .A1(s_mult_0_2_20), .B0(s_mult_0_3_19), 
        .B1(s_mult_0_3_20), .CI(co_mult_0_5_4), .COUT(co_mult_0_5_5), .S0(s_mult_0_5_19), 
        .S1(s_mult_0_5_20));

    FADD2B mult_0_add_5_6 (.A0(s_mult_0_2_21), .A1(s_mult_0_2_22), .B0(s_mult_0_3_21), 
        .B1(s_mult_0_3_22), .CI(co_mult_0_5_5), .COUT(co_mult_0_5_6), .S0(s_mult_0_5_21), 
        .S1(s_mult_0_5_22));

    FADD2B mult_0_add_5_7 (.A0(s_mult_0_2_23), .A1(s_mult_0_2_24), .B0(s_mult_0_3_23), 
        .B1(s_mult_0_3_24), .CI(co_mult_0_5_6), .COUT(co_mult_0_5_7), .S0(s_mult_0_5_23), 
        .S1(s_mult_0_5_24));

    FADD2B mult_0_add_5_8 (.A0(s_mult_0_2_25), .A1(s_mult_0_2_26), .B0(s_mult_0_3_25), 
        .B1(s_mult_0_3_26), .CI(co_mult_0_5_7), .COUT(co_mult_0_5_8), .S0(s_mult_0_5_25), 
        .S1(s_mult_0_5_26));

    FADD2B mult_0_add_5_9 (.A0(s_mult_0_2_27), .A1(s_mult_0_2_28), .B0(s_mult_0_3_27), 
        .B1(s_mult_0_3_28), .CI(co_mult_0_5_8), .COUT(co_mult_0_5_9), .S0(s_mult_0_5_27), 
        .S1(s_mult_0_5_28));

    FADD2B mult_0_add_5_10 (.A0(s_mult_0_2_29), .A1(scuba_vlo), .B0(s_mult_0_3_29), 
        .B1(s_mult_0_3_30), .CI(co_mult_0_5_9), .COUT(co_mult_0_5_10), .S0(s_mult_0_5_29), 
        .S1(s_mult_0_5_30));

    FADD2B mult_0_add_5_11 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(s_mult_0_3_31), 
        .B1(scuba_vlo), .CI(co_mult_0_5_10), .COUT(co_mult_0_5_11), .S0(s_mult_0_5_31), 
        .S1());

    FADD2B Cadd_t_mult_0_6_1 (.A0(scuba_vlo), .A1(s_mult_0_4_8), .B0(scuba_vlo), 
        .B1(mult_0_pp_4_8), .CI(scuba_vlo), .COUT(co_t_mult_0_6_1), .S0(), 
        .S1(Result[8]));

    FADD2B t_mult_0_add_6_2 (.A0(s_mult_0_4_9), .A1(s_mult_0_4_10), .B0(mult_0_pp_4_9), 
        .B1(s_mult_0_2_10), .CI(co_t_mult_0_6_1), .COUT(co_t_mult_0_6_2), 
        .S0(Result[9]), .S1(Result[10]));

    FADD2B t_mult_0_add_6_3 (.A0(s_mult_0_4_11), .A1(s_mult_0_4_12), .B0(s_mult_0_2_11), 
        .B1(s_mult_0_5_12), .CI(co_t_mult_0_6_2), .COUT(co_t_mult_0_6_3), 
        .S0(Result[11]), .S1(Result[12]));

    FADD2B t_mult_0_add_6_4 (.A0(s_mult_0_4_13), .A1(s_mult_0_4_14), .B0(s_mult_0_5_13), 
        .B1(s_mult_0_5_14), .CI(co_t_mult_0_6_3), .COUT(co_t_mult_0_6_4), 
        .S0(Result[13]), .S1(Result[14]));

    FADD2B t_mult_0_add_6_5 (.A0(s_mult_0_4_15), .A1(s_mult_0_4_16), .B0(s_mult_0_5_15), 
        .B1(s_mult_0_5_16), .CI(co_t_mult_0_6_4), .COUT(co_t_mult_0_6_5), 
        .S0(Result[15]), .S1(Result[16]));

    FADD2B t_mult_0_add_6_6 (.A0(s_mult_0_4_17), .A1(s_mult_0_4_18), .B0(s_mult_0_5_17), 
        .B1(s_mult_0_5_18), .CI(co_t_mult_0_6_5), .COUT(co_t_mult_0_6_6), 
        .S0(Result[17]), .S1(Result[18]));

    FADD2B t_mult_0_add_6_7 (.A0(s_mult_0_4_19), .A1(s_mult_0_4_20), .B0(s_mult_0_5_19), 
        .B1(s_mult_0_5_20), .CI(co_t_mult_0_6_6), .COUT(co_t_mult_0_6_7), 
        .S0(Result[19]), .S1(Result[20]));

    FADD2B t_mult_0_add_6_8 (.A0(s_mult_0_4_21), .A1(s_mult_0_4_22), .B0(s_mult_0_5_21), 
        .B1(s_mult_0_5_22), .CI(co_t_mult_0_6_7), .COUT(co_t_mult_0_6_8), 
        .S0(Result[21]), .S1(Result[22]));

    FADD2B t_mult_0_add_6_9 (.A0(s_mult_0_4_23), .A1(s_mult_0_4_24), .B0(s_mult_0_5_23), 
        .B1(s_mult_0_5_24), .CI(co_t_mult_0_6_8), .COUT(co_t_mult_0_6_9), 
        .S0(Result[23]), .S1(Result[24]));

    FADD2B t_mult_0_add_6_10 (.A0(s_mult_0_4_25), .A1(s_mult_0_4_26), .B0(s_mult_0_5_25), 
        .B1(s_mult_0_5_26), .CI(co_t_mult_0_6_9), .COUT(co_t_mult_0_6_10), 
        .S0(Result[25]), .S1(Result[26]));

    FADD2B t_mult_0_add_6_11 (.A0(s_mult_0_4_27), .A1(scuba_vlo), .B0(s_mult_0_5_27), 
        .B1(s_mult_0_5_28), .CI(co_t_mult_0_6_10), .COUT(co_t_mult_0_6_11), 
        .S0(Result[27]), .S1(Result[28]));

    FADD2B t_mult_0_add_6_12 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(s_mult_0_5_29), 
        .B1(s_mult_0_5_30), .CI(co_t_mult_0_6_11), .COUT(co_t_mult_0_6_12), 
        .S0(Result[29]), .S1(Result[30]));

    FADD2B t_mult_0_add_6_13 (.A0(scuba_vlo), .A1(scuba_vlo), .B0(s_mult_0_5_31), 
        .B1(scuba_vlo), .CI(co_t_mult_0_6_12), .COUT(co_t_mult_0_6_13), 
        .S0(Result[31]), .S1());

    MULT2 mult_0_mult_0_0 (.A0(DataA[0]), .A1(DataA[1]), .A2(DataA[1]), 
        .A3(DataA[2]), .B0(DataB[1]), .B1(DataB[0]), .B2(DataB[1]), .B3(DataB[0]), 
        .CI(mult_0_cin_lr_0), .P0(mult_0_pp_0_1), .P1(mult_0_pp_0_2), .CO(mco));

    MULT2 mult_0_mult_0_1 (.A0(DataA[2]), .A1(DataA[3]), .A2(DataA[3]), 
        .A3(DataA[4]), .B0(DataB[1]), .B1(DataB[0]), .B2(DataB[1]), .B3(DataB[0]), 
        .CI(mco), .P0(mult_0_pp_0_3), .P1(mult_0_pp_0_4), .CO(mco_1));

    MULT2 mult_0_mult_0_2 (.A0(DataA[4]), .A1(DataA[5]), .A2(DataA[5]), 
        .A3(DataA[6]), .B0(DataB[1]), .B1(DataB[0]), .B2(DataB[1]), .B3(DataB[0]), 
        .CI(mco_1), .P0(mult_0_pp_0_5), .P1(mult_0_pp_0_6), .CO(mco_2));

    MULT2 mult_0_mult_0_3 (.A0(DataA[6]), .A1(DataA[7]), .A2(DataA[7]), 
        .A3(DataA[8]), .B0(DataB[1]), .B1(DataB[0]), .B2(DataB[1]), .B3(DataB[0]), 
        .CI(mco_2), .P0(mult_0_pp_0_7), .P1(mult_0_pp_0_8), .CO(mco_3));

    MULT2 mult_0_mult_0_4 (.A0(DataA[8]), .A1(DataA[9]), .A2(DataA[9]), 
        .A3(DataA[10]), .B0(DataB[1]), .B1(DataB[0]), .B2(DataB[1]), .B3(DataB[0]), 
        .CI(mco_3), .P0(mult_0_pp_0_9), .P1(mult_0_pp_0_10), .CO(mco_4));

    MULT2 mult_0_mult_0_5 (.A0(DataA[10]), .A1(DataA[11]), .A2(DataA[11]), 
        .A3(DataA[12]), .B0(DataB[1]), .B1(DataB[0]), .B2(DataB[1]), .B3(DataB[0]), 
        .CI(mco_4), .P0(mult_0_pp_0_11), .P1(mult_0_pp_0_12), .CO(mco_5));

    MULT2 mult_0_mult_0_6 (.A0(DataA[12]), .A1(DataA[13]), .A2(DataA[13]), 
        .A3(DataA[14]), .B0(DataB[1]), .B1(DataB[0]), .B2(DataB[1]), .B3(DataB[0]), 
        .CI(mco_5), .P0(mult_0_pp_0_13), .P1(mult_0_pp_0_14), .CO(mco_6));

    MULT2 mult_0_mult_0_7 (.A0(DataA[14]), .A1(mult_0_mult_0_7_n2), .A2(mult_0_mult_0_7_n1), 
        .A3(scuba_vhi), .B0(DataB[1]), .B1(scuba_vhi), .B2(scuba_vhi), .B3(scuba_vhi), 
        .CI(mco_6), .P0(mult_0_pp_0_15), .P1(mult_0_pp_0_16), .CO(mfco));

    MULT2 mult_0_mult_2_0 (.A0(DataA[0]), .A1(DataA[1]), .A2(DataA[1]), 
        .A3(DataA[2]), .B0(DataB[3]), .B1(DataB[2]), .B2(DataB[3]), .B3(DataB[2]), 
        .CI(mult_0_cin_lr_2), .P0(mult_0_pp_1_3), .P1(mult_0_pp_1_4), .CO(mco_7));

    MULT2 mult_0_mult_2_1 (.A0(DataA[2]), .A1(DataA[3]), .A2(DataA[3]), 
        .A3(DataA[4]), .B0(DataB[3]), .B1(DataB[2]), .B2(DataB[3]), .B3(DataB[2]), 
        .CI(mco_7), .P0(mult_0_pp_1_5), .P1(mult_0_pp_1_6), .CO(mco_8));

    MULT2 mult_0_mult_2_2 (.A0(DataA[4]), .A1(DataA[5]), .A2(DataA[5]), 
        .A3(DataA[6]), .B0(DataB[3]), .B1(DataB[2]), .B2(DataB[3]), .B3(DataB[2]), 
        .CI(mco_8), .P0(mult_0_pp_1_7), .P1(mult_0_pp_1_8), .CO(mco_9));

    MULT2 mult_0_mult_2_3 (.A0(DataA[6]), .A1(DataA[7]), .A2(DataA[7]), 
        .A3(DataA[8]), .B0(DataB[3]), .B1(DataB[2]), .B2(DataB[3]), .B3(DataB[2]), 
        .CI(mco_9), .P0(mult_0_pp_1_9), .P1(mult_0_pp_1_10), .CO(mco_10));

    MULT2 mult_0_mult_2_4 (.A0(DataA[8]), .A1(DataA[9]), .A2(DataA[9]), 
        .A3(DataA[10]), .B0(DataB[3]), .B1(DataB[2]), .B2(DataB[3]), .B3(DataB[2]), 
        .CI(mco_10), .P0(mult_0_pp_1_11), .P1(mult_0_pp_1_12), .CO(mco_11));

    MULT2 mult_0_mult_2_5 (.A0(DataA[10]), .A1(DataA[11]), .A2(DataA[11]), 
        .A3(DataA[12]), .B0(DataB[3]), .B1(DataB[2]), .B2(DataB[3]), .B3(DataB[2]), 
        .CI(mco_11), .P0(mult_0_pp_1_13), .P1(mult_0_pp_1_14), .CO(mco_12));

    MULT2 mult_0_mult_2_6 (.A0(DataA[12]), .A1(DataA[13]), .A2(DataA[13]), 
        .A3(DataA[14]), .B0(DataB[3]), .B1(DataB[2]), .B2(DataB[3]), .B3(DataB[2]), 
        .CI(mco_12), .P0(mult_0_pp_1_15), .P1(mult_0_pp_1_16), .CO(mco_13));

    MULT2 mult_0_mult_2_7 (.A0(DataA[14]), .A1(mult_0_mult_2_7_n2), .A2(mult_0_mult_2_7_n1), 
        .A3(scuba_vlo), .B0(DataB[3]), .B1(scuba_vhi), .B2(scuba_vhi), .B3(DataB[2]), 
        .CI(mco_13), .P0(mult_0_pp_1_17), .P1(mult_0_pp_1_18), .CO(mfco_1));

    MULT2 mult_0_mult_4_0 (.A0(DataA[0]), .A1(DataA[1]), .A2(DataA[1]), 
        .A3(DataA[2]), .B0(DataB[5]), .B1(DataB[4]), .B2(DataB[5]), .B3(DataB[4]), 
        .CI(mult_0_cin_lr_4), .P0(mult_0_pp_2_5), .P1(mult_0_pp_2_6), .CO(mco_14));

    MULT2 mult_0_mult_4_1 (.A0(DataA[2]), .A1(DataA[3]), .A2(DataA[3]), 
        .A3(DataA[4]), .B0(DataB[5]), .B1(DataB[4]), .B2(DataB[5]), .B3(DataB[4]), 
        .CI(mco_14), .P0(mult_0_pp_2_7), .P1(mult_0_pp_2_8), .CO(mco_15));

    MULT2 mult_0_mult_4_2 (.A0(DataA[4]), .A1(DataA[5]), .A2(DataA[5]), 
        .A3(DataA[6]), .B0(DataB[5]), .B1(DataB[4]), .B2(DataB[5]), .B3(DataB[4]), 
        .CI(mco_15), .P0(mult_0_pp_2_9), .P1(mult_0_pp_2_10), .CO(mco_16));

    MULT2 mult_0_mult_4_3 (.A0(DataA[6]), .A1(DataA[7]), .A2(DataA[7]), 
        .A3(DataA[8]), .B0(DataB[5]), .B1(DataB[4]), .B2(DataB[5]), .B3(DataB[4]), 
        .CI(mco_16), .P0(mult_0_pp_2_11), .P1(mult_0_pp_2_12), .CO(mco_17));

    MULT2 mult_0_mult_4_4 (.A0(DataA[8]), .A1(DataA[9]), .A2(DataA[9]), 
        .A3(DataA[10]), .B0(DataB[5]), .B1(DataB[4]), .B2(DataB[5]), .B3(DataB[4]), 
        .CI(mco_17), .P0(mult_0_pp_2_13), .P1(mult_0_pp_2_14), .CO(mco_18));

    MULT2 mult_0_mult_4_5 (.A0(DataA[10]), .A1(DataA[11]), .A2(DataA[11]), 
        .A3(DataA[12]), .B0(DataB[5]), .B1(DataB[4]), .B2(DataB[5]), .B3(DataB[4]), 
        .CI(mco_18), .P0(mult_0_pp_2_15), .P1(mult_0_pp_2_16), .CO(mco_19));

    MULT2 mult_0_mult_4_6 (.A0(DataA[12]), .A1(DataA[13]), .A2(DataA[13]), 
        .A3(DataA[14]), .B0(DataB[5]), .B1(DataB[4]), .B2(DataB[5]), .B3(DataB[4]), 
        .CI(mco_19), .P0(mult_0_pp_2_17), .P1(mult_0_pp_2_18), .CO(mco_20));

    MULT2 mult_0_mult_4_7 (.A0(DataA[14]), .A1(mult_0_mult_4_7_n2), .A2(mult_0_mult_4_7_n1), 
        .A3(scuba_vlo), .B0(DataB[5]), .B1(scuba_vhi), .B2(scuba_vhi), .B3(DataB[4]), 
        .CI(mco_20), .P0(mult_0_pp_2_19), .P1(mult_0_pp_2_20), .CO(mfco_2));

    MULT2 mult_0_mult_6_0 (.A0(DataA[0]), .A1(DataA[1]), .A2(DataA[1]), 
        .A3(DataA[2]), .B0(DataB[7]), .B1(DataB[6]), .B2(DataB[7]), .B3(DataB[6]), 
        .CI(mult_0_cin_lr_6), .P0(mult_0_pp_3_7), .P1(mult_0_pp_3_8), .CO(mco_21));

    MULT2 mult_0_mult_6_1 (.A0(DataA[2]), .A1(DataA[3]), .A2(DataA[3]), 
        .A3(DataA[4]), .B0(DataB[7]), .B1(DataB[6]), .B2(DataB[7]), .B3(DataB[6]), 
        .CI(mco_21), .P0(mult_0_pp_3_9), .P1(mult_0_pp_3_10), .CO(mco_22));

    MULT2 mult_0_mult_6_2 (.A0(DataA[4]), .A1(DataA[5]), .A2(DataA[5]), 
        .A3(DataA[6]), .B0(DataB[7]), .B1(DataB[6]), .B2(DataB[7]), .B3(DataB[6]), 
        .CI(mco_22), .P0(mult_0_pp_3_11), .P1(mult_0_pp_3_12), .CO(mco_23));

    MULT2 mult_0_mult_6_3 (.A0(DataA[6]), .A1(DataA[7]), .A2(DataA[7]), 
        .A3(DataA[8]), .B0(DataB[7]), .B1(DataB[6]), .B2(DataB[7]), .B3(DataB[6]), 
        .CI(mco_23), .P0(mult_0_pp_3_13), .P1(mult_0_pp_3_14), .CO(mco_24));

    MULT2 mult_0_mult_6_4 (.A0(DataA[8]), .A1(DataA[9]), .A2(DataA[9]), 
        .A3(DataA[10]), .B0(DataB[7]), .B1(DataB[6]), .B2(DataB[7]), .B3(DataB[6]), 
        .CI(mco_24), .P0(mult_0_pp_3_15), .P1(mult_0_pp_3_16), .CO(mco_25));

    MULT2 mult_0_mult_6_5 (.A0(DataA[10]), .A1(DataA[11]), .A2(DataA[11]), 
        .A3(DataA[12]), .B0(DataB[7]), .B1(DataB[6]), .B2(DataB[7]), .B3(DataB[6]), 
        .CI(mco_25), .P0(mult_0_pp_3_17), .P1(mult_0_pp_3_18), .CO(mco_26));

    MULT2 mult_0_mult_6_6 (.A0(DataA[12]), .A1(DataA[13]), .A2(DataA[13]), 
        .A3(DataA[14]), .B0(DataB[7]), .B1(DataB[6]), .B2(DataB[7]), .B3(DataB[6]), 
        .CI(mco_26), .P0(mult_0_pp_3_19), .P1(mult_0_pp_3_20), .CO(mco_27));

    MULT2 mult_0_mult_6_7 (.A0(DataA[14]), .A1(mult_0_mult_6_7_n2), .A2(mult_0_mult_6_7_n1), 
        .A3(scuba_vlo), .B0(DataB[7]), .B1(scuba_vhi), .B2(scuba_vhi), .B3(DataB[6]), 
        .CI(mco_27), .P0(mult_0_pp_3_21), .P1(mult_0_pp_3_22), .CO(mfco_3));

    MULT2 mult_0_mult_8_0 (.A0(DataA[0]), .A1(DataA[1]), .A2(DataA[1]), 
        .A3(DataA[2]), .B0(DataB[9]), .B1(DataB[8]), .B2(DataB[9]), .B3(DataB[8]), 
        .CI(mult_0_cin_lr_8), .P0(mult_0_pp_4_9), .P1(mult_0_pp_4_10), .CO(mco_28));

    MULT2 mult_0_mult_8_1 (.A0(DataA[2]), .A1(DataA[3]), .A2(DataA[3]), 
        .A3(DataA[4]), .B0(DataB[9]), .B1(DataB[8]), .B2(DataB[9]), .B3(DataB[8]), 
        .CI(mco_28), .P0(mult_0_pp_4_11), .P1(mult_0_pp_4_12), .CO(mco_29));

    MULT2 mult_0_mult_8_2 (.A0(DataA[4]), .A1(DataA[5]), .A2(DataA[5]), 
        .A3(DataA[6]), .B0(DataB[9]), .B1(DataB[8]), .B2(DataB[9]), .B3(DataB[8]), 
        .CI(mco_29), .P0(mult_0_pp_4_13), .P1(mult_0_pp_4_14), .CO(mco_30));

    MULT2 mult_0_mult_8_3 (.A0(DataA[6]), .A1(DataA[7]), .A2(DataA[7]), 
        .A3(DataA[8]), .B0(DataB[9]), .B1(DataB[8]), .B2(DataB[9]), .B3(DataB[8]), 
        .CI(mco_30), .P0(mult_0_pp_4_15), .P1(mult_0_pp_4_16), .CO(mco_31));

    MULT2 mult_0_mult_8_4 (.A0(DataA[8]), .A1(DataA[9]), .A2(DataA[9]), 
        .A3(DataA[10]), .B0(DataB[9]), .B1(DataB[8]), .B2(DataB[9]), .B3(DataB[8]), 
        .CI(mco_31), .P0(mult_0_pp_4_17), .P1(mult_0_pp_4_18), .CO(mco_32));

    MULT2 mult_0_mult_8_5 (.A0(DataA[10]), .A1(DataA[11]), .A2(DataA[11]), 
        .A3(DataA[12]), .B0(DataB[9]), .B1(DataB[8]), .B2(DataB[9]), .B3(DataB[8]), 
        .CI(mco_32), .P0(mult_0_pp_4_19), .P1(mult_0_pp_4_20), .CO(mco_33));

    MULT2 mult_0_mult_8_6 (.A0(DataA[12]), .A1(DataA[13]), .A2(DataA[13]), 
        .A3(DataA[14]), .B0(DataB[9]), .B1(DataB[8]), .B2(DataB[9]), .B3(DataB[8]), 
        .CI(mco_33), .P0(mult_0_pp_4_21), .P1(mult_0_pp_4_22), .CO(mco_34));

    MULT2 mult_0_mult_8_7 (.A0(DataA[14]), .A1(mult_0_mult_8_7_n2), .A2(mult_0_mult_8_7_n1), 
        .A3(scuba_vlo), .B0(DataB[9]), .B1(scuba_vhi), .B2(scuba_vhi), .B3(DataB[8]), 
        .CI(mco_34), .P0(mult_0_pp_4_23), .P1(mult_0_pp_4_24), .CO(mfco_4));

    MULT2 mult_0_mult_10_0 (.A0(DataA[0]), .A1(DataA[1]), .A2(DataA[1]), 
        .A3(DataA[2]), .B0(DataB[11]), .B1(DataB[10]), .B2(DataB[11]), .B3(DataB[10]), 
        .CI(mult_0_cin_lr_10), .P0(mult_0_pp_5_11), .P1(mult_0_pp_5_12), 
        .CO(mco_35));

    MULT2 mult_0_mult_10_1 (.A0(DataA[2]), .A1(DataA[3]), .A2(DataA[3]), 
        .A3(DataA[4]), .B0(DataB[11]), .B1(DataB[10]), .B2(DataB[11]), .B3(DataB[10]), 
        .CI(mco_35), .P0(mult_0_pp_5_13), .P1(mult_0_pp_5_14), .CO(mco_36));

    MULT2 mult_0_mult_10_2 (.A0(DataA[4]), .A1(DataA[5]), .A2(DataA[5]), 
        .A3(DataA[6]), .B0(DataB[11]), .B1(DataB[10]), .B2(DataB[11]), .B3(DataB[10]), 
        .CI(mco_36), .P0(mult_0_pp_5_15), .P1(mult_0_pp_5_16), .CO(mco_37));

    MULT2 mult_0_mult_10_3 (.A0(DataA[6]), .A1(DataA[7]), .A2(DataA[7]), 
        .A3(DataA[8]), .B0(DataB[11]), .B1(DataB[10]), .B2(DataB[11]), .B3(DataB[10]), 
        .CI(mco_37), .P0(mult_0_pp_5_17), .P1(mult_0_pp_5_18), .CO(mco_38));

    MULT2 mult_0_mult_10_4 (.A0(DataA[8]), .A1(DataA[9]), .A2(DataA[9]), 
        .A3(DataA[10]), .B0(DataB[11]), .B1(DataB[10]), .B2(DataB[11]), 
        .B3(DataB[10]), .CI(mco_38), .P0(mult_0_pp_5_19), .P1(mult_0_pp_5_20), 
        .CO(mco_39));

    MULT2 mult_0_mult_10_5 (.A0(DataA[10]), .A1(DataA[11]), .A2(DataA[11]), 
        .A3(DataA[12]), .B0(DataB[11]), .B1(DataB[10]), .B2(DataB[11]), 
        .B3(DataB[10]), .CI(mco_39), .P0(mult_0_pp_5_21), .P1(mult_0_pp_5_22), 
        .CO(mco_40));

    MULT2 mult_0_mult_10_6 (.A0(DataA[12]), .A1(DataA[13]), .A2(DataA[13]), 
        .A3(DataA[14]), .B0(DataB[11]), .B1(DataB[10]), .B2(DataB[11]), 
        .B3(DataB[10]), .CI(mco_40), .P0(mult_0_pp_5_23), .P1(mult_0_pp_5_24), 
        .CO(mco_41));

    MULT2 mult_0_mult_10_7 (.A0(DataA[14]), .A1(mult_0_mult_10_7_n2), .A2(mult_0_mult_10_7_n1), 
        .A3(scuba_vlo), .B0(DataB[11]), .B1(scuba_vhi), .B2(scuba_vhi), 
        .B3(DataB[10]), .CI(mco_41), .P0(mult_0_pp_5_25), .P1(mult_0_pp_5_26), 
        .CO(mfco_5));

    MULT2 mult_0_mult_12_0 (.A0(DataA[0]), .A1(DataA[1]), .A2(DataA[1]), 
        .A3(DataA[2]), .B0(DataB[13]), .B1(DataB[12]), .B2(DataB[13]), .B3(DataB[12]), 
        .CI(mult_0_cin_lr_12), .P0(mult_0_pp_6_13), .P1(mult_0_pp_6_14), 
        .CO(mco_42));

    MULT2 mult_0_mult_12_1 (.A0(DataA[2]), .A1(DataA[3]), .A2(DataA[3]), 
        .A3(DataA[4]), .B0(DataB[13]), .B1(DataB[12]), .B2(DataB[13]), .B3(DataB[12]), 
        .CI(mco_42), .P0(mult_0_pp_6_15), .P1(mult_0_pp_6_16), .CO(mco_43));

    MULT2 mult_0_mult_12_2 (.A0(DataA[4]), .A1(DataA[5]), .A2(DataA[5]), 
        .A3(DataA[6]), .B0(DataB[13]), .B1(DataB[12]), .B2(DataB[13]), .B3(DataB[12]), 
        .CI(mco_43), .P0(mult_0_pp_6_17), .P1(mult_0_pp_6_18), .CO(mco_44));

    MULT2 mult_0_mult_12_3 (.A0(DataA[6]), .A1(DataA[7]), .A2(DataA[7]), 
        .A3(DataA[8]), .B0(DataB[13]), .B1(DataB[12]), .B2(DataB[13]), .B3(DataB[12]), 
        .CI(mco_44), .P0(mult_0_pp_6_19), .P1(mult_0_pp_6_20), .CO(mco_45));

    MULT2 mult_0_mult_12_4 (.A0(DataA[8]), .A1(DataA[9]), .A2(DataA[9]), 
        .A3(DataA[10]), .B0(DataB[13]), .B1(DataB[12]), .B2(DataB[13]), 
        .B3(DataB[12]), .CI(mco_45), .P0(mult_0_pp_6_21), .P1(mult_0_pp_6_22), 
        .CO(mco_46));

    MULT2 mult_0_mult_12_5 (.A0(DataA[10]), .A1(DataA[11]), .A2(DataA[11]), 
        .A3(DataA[12]), .B0(DataB[13]), .B1(DataB[12]), .B2(DataB[13]), 
        .B3(DataB[12]), .CI(mco_46), .P0(mult_0_pp_6_23), .P1(mult_0_pp_6_24), 
        .CO(mco_47));

    MULT2 mult_0_mult_12_6 (.A0(DataA[12]), .A1(DataA[13]), .A2(DataA[13]), 
        .A3(DataA[14]), .B0(DataB[13]), .B1(DataB[12]), .B2(DataB[13]), 
        .B3(DataB[12]), .CI(mco_47), .P0(mult_0_pp_6_25), .P1(mult_0_pp_6_26), 
        .CO(mco_48));

    MULT2 mult_0_mult_12_7 (.A0(DataA[14]), .A1(mult_0_mult_12_7_n2), .A2(mult_0_mult_12_7_n1), 
        .A3(scuba_vlo), .B0(DataB[13]), .B1(scuba_vhi), .B2(scuba_vhi), 
        .B3(DataB[12]), .CI(mco_48), .P0(mult_0_pp_6_27), .P1(mult_0_pp_6_28), 
        .CO(mfco_6));

    MULT2 mult_0_mult_14_0 (.A0(mult_0_mult_14_0_n0), .A1(DataA[1]), .A2(mult_0_mult_14_0_n1), 
        .A3(DataA[2]), .B0(scuba_vhi), .B1(DataB[14]), .B2(scuba_vhi), .B3(DataB[14]), 
        .CI(mult_0_cin_lr_14), .P0(mult_0_pp_7_15), .P1(mult_0_pp_7_16), 
        .CO(mco_49));

    MULT2 mult_0_mult_14_1 (.A0(mult_0_mult_14_1_n0), .A1(DataA[3]), .A2(mult_0_mult_14_1_n1), 
        .A3(DataA[4]), .B0(scuba_vhi), .B1(DataB[14]), .B2(scuba_vhi), .B3(DataB[14]), 
        .CI(mco_49), .P0(mult_0_pp_7_17), .P1(mult_0_pp_7_18), .CO(mco_50));

    MULT2 mult_0_mult_14_2 (.A0(mult_0_mult_14_2_n0), .A1(DataA[5]), .A2(mult_0_mult_14_2_n1), 
        .A3(DataA[6]), .B0(scuba_vhi), .B1(DataB[14]), .B2(scuba_vhi), .B3(DataB[14]), 
        .CI(mco_50), .P0(mult_0_pp_7_19), .P1(mult_0_pp_7_20), .CO(mco_51));

    MULT2 mult_0_mult_14_3 (.A0(mult_0_mult_14_3_n0), .A1(DataA[7]), .A2(mult_0_mult_14_3_n1), 
        .A3(DataA[8]), .B0(scuba_vhi), .B1(DataB[14]), .B2(scuba_vhi), .B3(DataB[14]), 
        .CI(mco_51), .P0(mult_0_pp_7_21), .P1(mult_0_pp_7_22), .CO(mco_52));

    MULT2 mult_0_mult_14_4 (.A0(mult_0_mult_14_4_n0), .A1(DataA[9]), .A2(mult_0_mult_14_4_n1), 
        .A3(DataA[10]), .B0(scuba_vhi), .B1(DataB[14]), .B2(scuba_vhi), 
        .B3(DataB[14]), .CI(mco_52), .P0(mult_0_pp_7_23), .P1(mult_0_pp_7_24), 
        .CO(mco_53));

    MULT2 mult_0_mult_14_5 (.A0(mult_0_mult_14_5_n0), .A1(DataA[11]), .A2(mult_0_mult_14_5_n1), 
        .A3(DataA[12]), .B0(scuba_vhi), .B1(DataB[14]), .B2(scuba_vhi), 
        .B3(DataB[14]), .CI(mco_53), .P0(mult_0_pp_7_25), .P1(mult_0_pp_7_26), 
        .CO(mco_54));

    MULT2 mult_0_mult_14_6 (.A0(mult_0_mult_14_6_n0), .A1(DataA[13]), .A2(mult_0_mult_14_6_n1), 
        .A3(DataA[14]), .B0(scuba_vhi), .B1(DataB[14]), .B2(scuba_vhi), 
        .B3(DataB[14]), .CI(mco_54), .P0(mult_0_pp_7_27), .P1(mult_0_pp_7_28), 
        .CO(mco_55));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    MULT2 mult_0_mult_14_7 (.A0(mult_0_mult_14_7_n0), .A1(mult_0_mult_14_7_n2), 
        .A2(DataA[15]), .A3(scuba_vlo), .B0(scuba_vhi), .B1(scuba_vhi), 
        .B2(DataB[15]), .B3(DataB[14]), .CI(mco_55), .P0(mult_0_pp_7_29), 
        .P1(mult_0_pp_7_30), .CO(mfco_7));

    assign Result[0] = mult_0_pp_0_0;
    assign Result[1] = mult_0_pp_0_1;
    assign Result[2] = s_mult_0_0_2;
    assign Result[3] = s_mult_0_0_3;
    assign Result[4] = s_mult_0_4_4;
    assign Result[5] = s_mult_0_4_5;
    assign Result[6] = s_mult_0_4_6;
    assign Result[7] = s_mult_0_4_7;


    // exemplar begin
    // exemplar end

endmodule
