/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 1.6 */
/* Mon Jan 02 18:22:07 2017 */

/* parameterized module instance */
sincos __ (.Clock( ), .ClkEn( ), .Reset( ), .Theta( ), .Sine( ));
